In [27]:
from sqlalchemy import create_engine, Column, Integer, String, Numeric, Text, Float
from sqlalchemy.orm import Session
from sqlalchemy.ext.automap import automap_base

import pandas as pd

In [28]:
file1="Resources/hawaii_measurements.csv"
file2="Resources/hawaii_stations.csv"

In [29]:
df1 = pd.read_csv(file1)
df2= pd.read_csv(file2)
df1=df1.fillna(0)
df1.head(15)
#df2.head(100)

        station        date  prcp  tobs
0   USC00519397  2010-01-01  0.08    65
1   USC00519397  2010-01-02  0.00    63
2   USC00519397  2010-01-03  0.00    74
3   USC00519397  2010-01-04  0.00    76
4   USC00519397  2010-01-06  0.00    73
5   USC00519397  2010-01-07  0.06    70
6   USC00519397  2010-01-08  0.00    64
7   USC00519397  2010-01-09  0.00    68
8   USC00519397  2010-01-10  0.00    73
9   USC00519397  2010-01-11  0.01    64
10  USC00519397  2010-01-12  0.00    61
11  USC00519397  2010-01-14  0.00    66
12  USC00519397  2010-01-15  0.00    65
13  USC00519397  2010-01-16  0.00    68
14  USC00519397  2010-01-17  0.00    64